import { AWSS3Img,
  BootstrapImg,
  CSSImg,
  ExpressJSImg,
  GitImg,
  HTMLImg,
  JSImg,
  JavaImg,
  JestImg,
  MicroFrontendImg,
  MochaChaiImg,
  NodeJSImg,
  OracleImg,
  ReactImg,
  ReduxImg,
  SASSImg,
  TypeORMImg,
  TypeScriptImg,
  Webpack5Img } from "../../assets/images";


export const SKILL_ICONS_MAP = {
  HTML: HTMLImg,
  CSS: CSSImg,
  JAVASCRIPT: JSImg,
  "REACT.JS": ReactImg,
  TYPESCRIPT: TypeScriptImg,
  REDUX: ReduxImg,
  BOOTSTRAP: BootstrapImg,
  "NODE.JS": NodeJSImg,
  "EXPRESS.JS": ExpressJSImg,
  "WEBPACK 5": Webpack5Img,
  "MICRO FRONTENDS": MicroFrontendImg,
  SCSS: SASSImg,
  TYPEORM: TypeORMImg,
  "AWS S3": AWSS3Img,
  JEST: JestImg,
  "MOCHA-CHAI": MochaChaiImg,
  JAVA: JavaImg,
  "ORACLE DB": OracleImg,
  GIT: GitImg,
};
